-- MySQL Script generated by MySQL Workbench
-- Wed Feb 16 13:35:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_PI
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_PI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_PI` DEFAULT CHARACTER SET utf8 ;
USE `db_PI` ;

-- -----------------------------------------------------
-- Table `db_PI`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_PI`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_u` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_PI`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_PI`.`tb_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_c` VARCHAR(150) NOT NULL,
  `descricao_c` VARCHAR(500) NOT NULL,
  `tb_usuario_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_categoria_tb_usuario_idx` (`tb_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_categoria_tb_usuario`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `db_PI`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_PI`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_PI`.`tb_produtos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome_p` VARCHAR(150) NOT NULL,
  `descricao` VARCHAR(5000) NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `duracao` INT NOT NULL,
  `tb_categoria_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produtos_tb_categoria1_idx` (`tb_categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_categoria1`
    FOREIGN KEY (`tb_categoria_id`)
    REFERENCES `db_PI`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
